@startuml
Player -- Game : plays
Game -- Main  : containes
Main -- Player : rolls
Gamelogic -- Game : evaluates


Player : name
Player : score()
Main : getFacevalue()
Main : roll()
Game : instructions
Gamelogic : sumTotal()
Gamelogic : winningCondition

@enduml